server:
  port: ${service.authenticationservice.port}

spring:
  jpa:
    database: hsql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${service.hsqldb.path}\authenticationservice_db
    username: SA
    password:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${service.zipkinserver.uri}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${service.eurekaserver.uri}

management:
  endpoints:
    web:
      exposure:
        include: refresh