example.property: "I AM A DEV PROPERTY OVERRIDE"

server:
  port: 9191
  security:
    enable: false

spring:
  jpa:
    database: hsql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:hsqldb:file:F:\data\learncloud\licensingservice_db
    username: SA
    password:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.7
      bindings:
        inboundOrgChanges:
          contentType: application/json
          destination: orgChangeTopic
          group: licensingGroup

eureka:
  instance:
    hostname: 192.168.1.7
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9192/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh

security:
  oauth2:
    resource:
      user-info-uri: http://192.168.1.7:9194/authenticationservice/user