example.property: "I AM A DEV PROPERTY OVERRIDE"

server:
  port: 9091
  security:
    enable: false

spring:
  jpa:
    database: hsql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:hsqldb:file:F:\data\learncloud\licensingservice_db
    username: SA
    password:

eureka:
  instance:
    hostname: 192.168.1.7
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9092/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh