server:
  port: ${service.specialrouteservice.port}

spring:
  jpa:
    database: hsql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${service.hsqldb.path}\specialroute_db
    username: SA
    password:

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${service.eurekaserver.uri}

management:
  endpoints:
    web:
      exposure:
        include: refresh