server:
  port: 9194

eureka:
  instance:
    hostname: 192.168.1.7
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9192/eureka

zuul:
  sensitiveHeaders: Cookie,Set-Cookie  # 设置该值用于传播请求头的参数

management:
  endpoints:
    web:
      exposure:
        include: routes,refresh