server:
  port: ${service.zuulserver.port}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${service.eurekaserver.uri}

zuul:
  sensitiveHeaders: Cookie,Set-Cookie  # 设置该值用于传播请求头的参数

management:
  endpoints:
    web:
      exposure:
        include: routes,refresh

spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${service.zipkinserver.uri}